"""empty message

Revision ID: 8eda70283b3b
Revises: a1517b8f2745
Create Date: 2025-10-07 10:09:33.581349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eda70283b3b'
down_revision = 'a1517b8f2745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_facility_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'facility', ['source_facility_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_facility_id')

    # ### end Alembic commands ###
