"""empty message

Revision ID: a1517b8f2745
Revises: c9475a91a759
Create Date: 2025-10-07 07:50:17.872402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1517b8f2745'
down_revision = 'c9475a91a759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_transfer_destination', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transaction', schema=None) as batch_op:
        batch_op.drop_column('is_transfer_destination')

    # ### end Alembic commands ###
