"""empty message

Revision ID: c9475a91a759
Revises: 
Create Date: 2025-10-07 06:51:57.330816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9475a91a759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transaction', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
